spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: gulimall-third-party
alibaba:
  cloud:
    access-key: LTAI4G8wcNq6Q9RTQD5oDEk6
    secret-key: sFDwl3rV95bS8ZTK97c5H6MHFIi0Xs
    oss:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      bucket: gulimall-methenberg

server:
  port: 30000